apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/curtis736/openyard
    newName: openyard
    newTag: local
# kindnet + hostPort ingress-nginx : NP trop stricte → 503 sur l’Ingress
patches:
  - path: delete-networkpolicy.yaml
    target:
      kind: NetworkPolicy
      name: openyard-control
