apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openyard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openyard.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENYARD_API_KEY: {{ .Values.apiKey | quote }}
