apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-echo
  namespace: openyard
  labels:
    app.kubernetes.io/name: demo-echo
    openyard.io/tenant: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-echo
        openyard.io/tenant: demo
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0
          args: ["-listen=:5678", "-text=openyard-demo-echo"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5678
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: demo-echo
  namespace: openyard
  labels:
    app.kubernetes.io/name: demo-echo
    openyard.io/tenant: demo
spec:
  selector:
    app.kubernetes.io/name: demo-echo
  ports:
    - name: http
      port: 80
      targetPort: http
