apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openyard-control
  namespace: openyard
  labels:
    app.kubernetes.io/name: openyard-control
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: openyard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openyard-control
                port:
                  name: http
