apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openyard-control
  namespace: openyard
  labels:
    app.kubernetes.io/name: openyard-control
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openyard-control
