apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openyard-data
  namespace: openyard
  labels:
    app.kubernetes.io/name: openyard-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
