apiVersion: v1
kind: ResourceQuota
metadata:
  name: openyard-quota
  namespace: openyard
  labels:
    app.kubernetes.io/part-of: openyard
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    services: "15"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: openyard-limits
  namespace: openyard
  labels:
    app.kubernetes.io/part-of: openyard
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 512Mi
