apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openyard-obs
resources:
  - namespace.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboard.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: openyard
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
